### ISSUE TITLE
[Not Scaffolded] Implement new user registration

### ISSUE THREAD

**Issue by SohamG** [lugatuic/cerberus#6]
We need to find a way to verify users. I am thinking ask them to login with discord.

**Comment by ThatMarko** [comment]
Are you thinking about implementing it from scratch? There are quite a few good projects that handle auth with SvelteKit. For example: https://next-auth.js.org/

**Comment by SohamG** [comment]
This app's purpose is to interface with AD/LDAP so I don't really want to "Login with Discord". Right now I am working on a simple JWT setup in the jwt-auth branch. What needs figuring out is how to "verify" new users - I am thinking asking them to associate their discord account and check their presence in ACM/LUG discords. 

A possible second option is to have manual verification of new accounts created in the app (perhaps before they hit LDAP).

**Comment by SohamG** [comment]
Implemented
